### PR TITLE
feat: point recipe links directly to the item page

### LINKED ISSUE #15: XIVDB Links Broken
It appears the links to recipes/items are broken to XIVDB.

For example, upon clicking on Holy Rainbow Work Gloves,  I am taken to http://xivdb.com/recipe/2749 which appears to be an incomplete URL.  The complete URL is http://xivdb.com/item/11994/holy+rainbow+work+gloves.

### PR DESCRIPTION
**Pull request by aluink**
An attempt to resolve #15.

### CODE REVIEW

**Comment by Supamiu** [comment]
You should ammend your commit to reset author on it, it has another name than the github account you used for the PR.

**Comment by Supamiu** [comment]
Just waiting for you to amend the commit (unless you want to commit with this user name) and I'll merge it.

If you have any troubles amending the commit, I'm available on discord (https://discord.gg/r6qxt6P) to help you.

**Comment by aluink** [comment]
Yeah, I did this from work.  That's probably the issue.  I'll update the local config and amend.  That or I'll do it at home.

In passing, I didn't know how to properly test my changes. Being new to Angular, I'm assuming there are no tests as I don't see any.  Correct?  I assumed since the function in question is private, that it wasn't used elsewhere.

**Comment by Supamiu** [comment]
Yup there are no tests at the moment, adding some is definetly on the roadmap.

I tested it from my place and it worked like a charm, and this method is not used anywhere else, even if it should be, but that'll be in the refactoring process :smile:

I'll go to sleep soon (30mins max) so if you want a merge before tomorrow (in ~9 hours), amend it before I go 👍

**Comment by aluink** [comment]
Too late for today, but I've amended.

**Pull request merged**
